"""add databases

Revision ID: b89e9177fd10
Revises: f26e693efe17
Create Date: 2024-02-13 15:55:09.823595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b89e9177fd10'
down_revision = 'f26e693efe17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index('uq_tickets_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index('uq_tickets_title', ['title'], unique=False)

    # ### end Alembic commands ###
