"""add databases

Revision ID: f26e693efe17
Revises: 10656f832672
Create Date: 2024-02-13 15:49:06.163225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f26e693efe17'
down_revision = '10656f832672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
