version: '3'
services:
  phpmyadmin:
    container_name: phpmyadmin
    hostname: phpmyadmin
    image: phpmyadmin:5.2.1
    restart: always
    links:
      - mysql_db
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql_db
      - MYSQL_USERNAME=mainroot
      - MYSQL_ROOT_PASSWORD=secret
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
      
  mysql_db:
    container_name: mysql_db
    hostname: mysql_db
    image: mysql:8.1.0
    ports:
      - "32001:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=cinema
      - MYSQL_PASSWORD=secret
      - MYSQL_USER=mainroot
    volumes:
      - mysql:/var/lib/mysql

  wsgi_app:
    container_name: wsgi_app
    hostname: wsgi_app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    restart: always

volumes:
  mysql: